version: "3.9"
services:

  postgres:
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - billing_db:/var/lib/postgresql/data
    env_file:
      - ./postgres/.env
    networks:
      - backend

  redis:
    image: redis:6.2.6
    volumes:
      - redisdata:/data
    env_file:
      - ./redis/.env
    networks:
      - backend

  django:
    build:
      context: ./django
      dockerfile: ./Dockerfile
    command: sh -c "sleep 5 && python manage.py migrate && python manage.py collectstatic --no-input && gunicorn config.wsgi -b 0.0.0.0:8000 --timeout 900 --chdir=/code"
    volumes:
      - static:/code/static
    env_file:
      - ./django/.env
    depends_on:
      - postgres
    networks:
      - backend

  celery:
    build:
      context: ./django
      dockerfile: ./Dockerfile
    command: sh -c "sleep 5 && celery -A config worker -B -l INFO"
    env_file:
      - ./django/.env
    depends_on:
      - postgres
      - redis
    networks:
      - backend

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - static:/var/www/static/
    depends_on:
      - django
    ports:
      - 80:80
    restart: always
    networks:
      - backend

volumes:
  static:
  billing_db:
  redisdata:


networks:
  backend:
