# Generated by Django 4.1.2 on 2022-10-21 14:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price')),
                ('period', models.DecimalField(blank=True, decimal_places=0, max_digits=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='period')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(verbose_name='user id')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('paid', models.DateTimeField(blank=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
