# Generated by Django 4.1.2 on 2022-10-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='itemstopayments',
            constraint=models.UniqueConstraint(fields=('item_id', 'payment_id'), name='item_payment_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemstousers',
            constraint=models.UniqueConstraint(fields=('item_id', 'user_id'), name='item_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='permissionstoitems',
            constraint=models.UniqueConstraint(fields=('item_id', 'permission_id'), name='item_permission_idx'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(fields=('item_id', 'currency'), name='item_price_currency_idx'),
        ),
    ]
