# Generated by Django 4.1.2 on 2022-11-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_renewable_field_to_i2u_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstousers',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
